PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

DROP TABLE IF EXISTS anketa;
CREATE TABLE anketa (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, name VARCHAR (32),  lastname VARCHAR(32),age INT);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
